import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get('window')

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
    paddingBottom: 10,
    paddingTop: 36,
  },
  container: {
    padding: '5%',
  },
  categoriasContainer: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    marginTop: 30,
    marginBottom: 20,
  },
  categoriaTag: {
    paddingBottom: 12,
    paddingHorizontal: 16,
    marginRight: 20,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  },
  categoriaAtiva: {
    borderBottomColor: '#1ab394',
  },
  categoriaTexto: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
  },
  categoriaTextoAtivo: {
    color: '#1ab394',
  },
  suggestedWorkout: {
    flexDirection: 'row',
    backgroundColor: '#f2f8f6',
    borderRadius: 16,
    padding: 14,
    marginBottom: 24,
    alignItems: 'center',
  },
  suggestedImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
    overflow: 'hidden',
  },
  overlay: { ...StyleSheet.absoluteFillObject, borderRadius: 12 },
  suggestedTextContainer: { flex: 1, marginLeft: 12 },
  suggestedTitle: { fontWeight: 'bold', fontSize: 18, color: '#222' },
  suggestedButton: {
    backgroundColor: '#1ab394',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  suggestedButtonText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginTop: 40,
    marginBottom: 14,
    color: '#222',
  },
  quickCard: {
    width: width * 0.45,
    height: 130,
    borderRadius: 16,
    marginRight: 14,
    overflow: 'hidden',
  },
  quickImage: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  quickOverlay: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
  },
  quickCardTitle: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  quickCardTime: { color: '#eee', fontSize: 12, marginTop: 4 },
  challengeContainer: { flexDirection: 'row', justifyContent: 'space-between' },
  challengeCard: {
    width: width * 0.42,
    height: 160,
    borderRadius: 16,
    overflow: 'hidden',
  },
  challengeOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 16,
    borderRadius: 16,
  },
  challengeTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 6,
  },
  challengeSubtitle: { fontSize: 13, color: '#fff' },
  challengeProgress: {
    backgroundColor: 'rgba(255,255,255,0.3)',
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  challengeProgressText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  videoOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoContainer: {
    width: '90%',
    height: '60%',
    backgroundColor: '#000',
    borderRadius: 12,
    overflow: 'hidden',
  },
  closeButton: { position: 'absolute', top: 10, right: 10, padding: 5 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalOptionText: {
    fontSize: 16,
    color: '#222',
  },

modalClose: {
  position: 'absolute',
  top: 40,
  right: 20,
  padding: 10,
  backgroundColor: '#fff',
  borderRadius: 8,
},
modalCloseText: {
  color: '#333',
  fontWeight: 'bold',
},
webview: {
  width: '90%',
  height: '70%',
  borderRadius: 12,
  overflow: 'hidden',
},
})